### ISSUE TITLE
 Build failed with an exception on adding smileId sdk to Flutter app

### ISSUE THREAD

**Issue by Tolulope05** [smileidentity/android#289]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':smile_id:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Internal compiler error. See log for more details

**Comment by vanshg** [comment]
Hi @Tolulope05, could you please provide additional details? Which SDK version are you attempting to add? The error message you posted indicates there should be more logs -- could you provide those?

Separately, if you're using Flutter, you should look into using our Flutter SDK (https://github.com/smileidentity/flutter)

**Comment by vanshg** [comment]
The error message indicates an "Internal compiler error". Could you please detail your build environment and also paste the full stack trace?

**Comment by Tolulope05** [comment]
at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(Unknown Source)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(Unknown Source)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoSuchMethodError: 'void org.jetbrains.kotlin.cli.common.messages.MessageCollector.report$default(org.jetbrains.kotlin.cli.common.messages.MessageCollector, org.jetbrains.kotlin.cli.common.messages.CompilerMessageSeverity, java.lang.String, org.jetbrains.kotlin.cli.common.messages.CompilerMessageSourceLocation, int, java.lang.Object)'
	at androidx.compose.compiler.plugins.kotlin.ComposePluginRegistrar$Companion.checkCompilerVersion(ComposePlugin.kt:264)
	... 39 more
...:39


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':smile_id:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Internal compiler error. See log for more details

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 23s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by Tolulope05** [comment]
Note: Recompile with -Xlint:deprecation for details.
e: java.lang.Error: Something went wrong while checking for version compatibility between the Compose Compiler and the Kotlin Compiler.  It is possible that the versions are incompatible.  Please verify your kotlin version  and consult the Compose-Kotlin compatibility map located at https://developer.android.com/jetpack/androidx/releases/compose-kotlin
	at androidx.compose.compiler.plugins.kotlin.ComposePluginRegistrar$Companion.checkCompilerVersion(ComposePlugin.kt:286)

**Comment by Tolulope05** [comment]
For ios

``` Errno::ENOENT - No such file or directory @ rb_sysopen - /Users/Tolulope/Studio Project/monietree-mobile-app/ios/Pods/Local Podspecs/qoreidsdk.podspec.json

**Comment by Tolulope05** [comment]
Solution: 
// Update kotlin version to 1.9.10 and build gradle to 7.3.0
// android>build.gradle

buildscript {
    ext.kotlin_version = '1.9.10'
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:7.3.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}
